# TÍTULOS
label.titulo.pagina.consulta=Agendas Cadastradas
label.titulo.pagina.cadastro=Cadastro de Agenda
label.titulo.pagina.atualizacao=Atualização de Agenda

# AÇÕES
label.nova=Nova Agenda
label.editar.agenda=Editar Agenda

# CAMPOS
label.periodo.disponivel=PERÍODO DISPONÍVEL
label.periodo.disponivel.form=Período Disponível:

# MENSAGENS
label.modal.corpo=Deseja excluir esta agenda?
