# TÍTULOS
label.titulo.pagina.consulta=Compromissos Cadastrados
label.titulo.pagina.cadastro=Cadastro de Compromisso
label.titulo.pagina.atualizacao=Atualização de Compromisso

# AÇÕES
label.novo=Novo Compromisso
label.editar.compromisso=Editar Compromisso

# TABELA
label.funcionario=FUNCIONÁRIO
label.agenda=AGENDA
label.data=DATA
label.horario=HORÁRIO

# FORMULÁRIO
label.funcionario.form=Funcionário:
label.agenda.form=Agenda:
label.data.form=Data:
label.horario.form=Horário:

# MENSAGENS
label.modal.corpo=Deseja excluir este compromisso?