# TÍTULOS
label.titulo.pagina.consulta=Funcionários Cadastrados
label.titulo.pagina.cadastro=Cadastro de Funcionário
label.titulo.pagina.atualizacao=Atualização de Funcionário

# AÇÕES
label.novo=Novo Funcionário
label.editar.funcionario=Editar Funcionário

# MENSAGENS
label.modal.corpo=Deseja excluir este funcionário?
