# TÍTULOS
label.titulo.pagina.relatorio=Relatório de Compromissos

# AÇÕES
label.gerar.relatorio=Gerar Relatório
label.exportar.excel=Exportar Excel

# CAMPOS
label.data.inicial.form=Data Inicial:
label.data.final.form=Data Final:

# TABELA
label.codigo.funcionario=CÓDIGO FUNCIONÁRIO
label.codigo.agenda=CÓDIGO AGENDA
