# APLICAÇÃO
label.aplicacao=Organiza+

# NAVEGAÇÃO
menu.funcionarios=Funcionários
menu.agendas=Agendas
menu.compromissos=Compromissos
menu.relatorios=Relatórios

# AÇÕES
label.novo=NOVO
label.editar=EDITAR
label.excluir=EXCLUIR
label.salvar=Salvar
label.limpar.formulario=Limpar Formulário
label.sim=SIM
label.nao=NÃO
label.voltar=Voltar

# CONSULTA
label.id=ID
label.nome=NOME
label.acao=AÇÃO
label.buscar.por=BUSCAR POR
label.escolha=ESCOLHA...
label.pesquisar=PESQUISAR

# FORMULÁRIO
label.id.form=Id:
label.nome.form=Nome:
label.selecione=Selecione...

# MODAIS
label.modal.titulo=Confirmação de Exclusão